package com.autoedit.ui;

import android.content.*;import android.graphics.*;import android.net.Uri;import android.view.*;import com.autoedit.model.*;import com.autoedit.engine.*;import java.io.*;

public class PreviewView extends View {
    public EditProject project; private final FormulaEngine formulas=new FormulaEngine(); private final EffectEngine effects=new EffectEngine(); private long startMs=0; public boolean playing=false; private Bitmap current;
    public PreviewView(Context c){ super(c); setBackgroundColor(0xff020409); }
    public void play(){ playing=true; startMs=System.currentTimeMillis(); invalidate(); }
    public void pause(){ playing=false; invalidate(); }
    @Override protected void onDraw(Canvas canvas){ super.onDraw(canvas); Paint p=new Paint(Paint.ANTI_ALIAS_FLAG); p.setColor(0xff071422); canvas.drawRoundRect(10,10,getWidth()-10,getHeight()-10,28,28,p); if(project==null||project.clips.isEmpty()){ drawCentered(canvas,"Import images to begin",0xff8dcaff); return; } float t=playing?((System.currentTimeMillis()-startMs)/1000f)%Math.max(1,project.totalDurationSec()):0; TimelineClip clip=null; float acc=0; for(TimelineClip c:project.clips){ if(t<=acc+c.durationSec){ clip=c; break;} acc+=c.durationSec; } if(clip==null) clip=project.clips.get(0); float prog=Math.min(1,Math.max(0,(t-acc)/clip.durationSec)); try{ if(current!=null) current.recycle(); current=decode(Uri.parse(clip.uri),getWidth(),getHeight()); if(current!=null){ KeyframeState st=formulas.stateAt(clip.formula,prog); RectF dst=fit(current.getWidth(),current.getHeight(),getWidth(),getHeight(),st); canvas.drawBitmap(current,null,dst,effects.paintFor(clip.effect,clip.effectIntensity)); effects.drawPost(canvas,getWidth(),getHeight(),clip.effect,clip.effectIntensity); } }catch(Exception e){ drawCentered(canvas,"Missing/unsupported image",0xffff8080); } p.setColor(0xffffffff); p.setTextSize(30); canvas.drawText(String.format("Clip %02d  %.1fs",clip.index,clip.durationSec),28,getHeight()-28,p); if(playing) postInvalidateDelayed(33); }
    private void drawCentered(Canvas c,String s,int color){ Paint p=new Paint(Paint.ANTI_ALIAS_FLAG); p.setColor(color); p.setTextSize(34); p.setTextAlign(Paint.Align.CENTER); c.drawText(s,getWidth()/2f,getHeight()/2f,p); }
    private RectF fit(int sw,int sh,int w,int h,KeyframeState st){ float scale=Math.max(w/(float)sw,h/(float)sh)*st.scale; float dw=sw*scale,dh=sh*scale,cx=w/2f+st.x*w,cy=h/2f+st.y*h; return new RectF(cx-dw/2,cy-dh/2,cx+dw/2,cy+dh/2); }
    private Bitmap decode(Uri uri,int tw,int th) throws IOException{ BitmapFactory.Options b=new BitmapFactory.Options(); b.inJustDecodeBounds=true; try(InputStream is=getContext().getContentResolver().openInputStream(uri)){ BitmapFactory.decodeStream(is,null,b); } BitmapFactory.Options o=new BitmapFactory.Options(); int s=1; while(b.outWidth/(s*2)>tw && b.outHeight/(s*2)>th) s*=2; o.inSampleSize=s; try(InputStream is=getContext().getContentResolver().openInputStream(uri)){ return BitmapFactory.decodeStream(is,null,o); } }
}
