package com.autoedit.model;

public enum EffectType { NONE, BLUR, MOTION_BLUR, GLOW, SOFT_GLOW, VIGNETTE, FILM_GRAIN, SHARPEN, BRIGHTNESS, CONTRAST, SATURATION, TEMPERATURE, EXPOSURE, HIGHLIGHTS, SHADOWS, FADE, BLACK_WHITE, SEPIA, CINEMATIC, DREAM, VINTAGE, FILM, SOFT_FOCUS }
