package com.autoedit.model;

public enum TransitionType {
    NONE, FADE, CROSS_DISSOLVE, ZOOM, ZOOM_BLUR, SLIDE_LEFT, SLIDE_RIGHT, SLIDE_UP, SLIDE_DOWN,
    PUSH_LEFT, PUSH_RIGHT, PUSH_UP, PUSH_DOWN, WIPE_LEFT, WIPE_RIGHT, WIPE_UP, WIPE_DOWN,
    CIRCLE_REVEAL, RADIAL_REVEAL, BLUR_TRANSITION, FLASH, SMOOTH_LIGHT, CINEMATIC_BLUR
}
