package com.autoedit;

import android.app.*;import android.os.*;import android.content.*;import android.net.*;import android.provider.Settings;import android.view.*;import android.widget.*;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import java.util.*;
import com.autoedit.model.*;import com.autoedit.engine.*;import com.autoedit.project.*;import com.autoedit.export.*;import com.autoedit.ui.*;

public class MainActivity extends Activity {
    private static final int PICK_IMAGES=10, PICK_AUDIO=11; private final int blue=0xff49A8FF, bg=0xff020409, card=0xff071422;
    private EditProject project; private ProjectStore store; private FormulaEngine formulas; private LinearLayout timeline; private TextView status; private PreviewView preview; private int selected=-1; private final Handler autosaveHandler=new Handler(Looper.getMainLooper()); private final Runnable autosave=new Runnable(){ public void run(){ if(store!=null&&project!=null) store.save(project); autosaveHandler.postDelayed(this,30000); } };
    private final BroadcastReceiver exportReceiver=new BroadcastReceiver(){ public void onReceive(Context c,Intent i){ int p=i.getIntExtra("percent",0); String m=i.getStringExtra("message"); status.setText(p<0?"Export failed: "+m:"Export "+p+"% • "+m); }};
    @Override public void onCreate(Bundle b){ super.onCreate(b); store=new ProjectStore(this); formulas=new FormulaEngine(); project=store.load(); buildUi(); autosaveHandler.postDelayed(autosave,30000); }
    @Override protected void onResume(){ super.onResume(); if(Build.VERSION.SDK_INT>=33) registerReceiver(exportReceiver,new IntentFilter(ExportService.ACTION_PROGRESS),RECEIVER_NOT_EXPORTED); else registerReceiver(exportReceiver,new IntentFilter(ExportService.ACTION_PROGRESS)); }
    @Override protected void onPause(){ super.onPause(); try{unregisterReceiver(exportReceiver);}catch(Exception ignored){} store.save(project); }
    @Override protected void onDestroy(){ super.onDestroy(); autosaveHandler.removeCallbacks(autosave); }
    private void buildUi(){ LinearLayout root=new LinearLayout(this); root.setOrientation(LinearLayout.VERTICAL); root.setPadding(18,18,18,18); root.setBackgroundColor(bg); setContentView(root);
        LinearLayout top=new LinearLayout(this); top.setGravity(Gravity.CENTER_VERTICAL); top.setPadding(0,0,0,12); ImageView logo=new ImageView(this); logo.setImageResource(getResources().getIdentifier("ic_auto_edit","drawable",getPackageName())); top.addView(logo,new LinearLayout.LayoutParams(64,64)); TextView title=txt("  AUTO EDIT\nTurn Your Images Into Motion",22,0xffffffff); top.addView(title,new LinearLayout.LayoutParams(0,-2,1)); root.addView(top);
        preview=new PreviewView(this); preview.project=project; root.addView(preview,new LinearLayout.LayoutParams(-1,0,3));
        LinearLayout controls=row(); addBtn(controls,"＋ IMAGES",v->pickImages()); addBtn(controls,"▶ / Ⅱ",v->{ if(preview.playing) preview.pause(); else preview.play(); }); addBtn(controls,"♫ AUDIO",v->pickAudio()); addBtn(controls,"⤓ EXPORT",v->exportDialog()); root.addView(controls);
        HorizontalScrollView toolsScroll=new HorizontalScrollView(this); LinearLayout tools=row(); toolsScroll.addView(tools); addBtn(tools,"⏱ Duration",v->durationDialog()); addBtn(tools,"↗ Formula",v->formulaDialog()); addBtn(tools,"↔ Transition",v->transitionDialog()); addBtn(tools,"✦ Effects",v->effectDialog()); addBtn(tools,"T Text",v->textDialog()); addBtn(tools,"⚡ Auto Edit",v->autoEditDialog()); addBtn(tools,"⧉ Copy/Paste",v->toast("Style copy/paste: select a clip, use formula/effect/transition apply to selected/all.")); addBtn(tools,"↶ Undo",v->toast("Auto-save is active every 30 seconds.")); root.addView(toolsScroll);
        status=txt("Ready • "+project.clips.size()+" clips • "+project.totalDurationSec()+" sec",14,0xffb9e1ff); root.addView(status);
        HorizontalScrollView hsv=new HorizontalScrollView(this); timeline=new LinearLayout(this); timeline.setOrientation(LinearLayout.HORIZONTAL); hsv.addView(timeline); root.addView(hsv,new LinearLayout.LayoutParams(-1,150)); refreshTimeline(); }
    private void refreshTimeline(){ timeline.removeAllViews(); project.renumber(); for(int i=0;i<project.clips.size();i++){ TimelineClip c=project.clips.get(i); TextView v=txt(String.format(Locale.US,"⋮⋮  [%02d]\n%.1fs badge\nF%s",c.index,c.durationSec,c.formula.id),13,0xffffffff); v.setGravity(Gravity.CENTER); v.setBackgroundColor(i==selected?blue:card); final int ix=i; v.setOnClickListener(x->{ selected=ix; refreshTimeline(); }); v.setOnLongClickListener(x->{ removeOrMoveDialog(ix); return true; }); LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(112,128); lp.setMargins(4,4,4,4); timeline.addView(v,lp); } status.setText("Ready • "+project.clips.size()+" clips • "+String.format(Locale.US,"%.1f",project.totalDurationSec())+" sec"); preview.invalidate(); }
    private void pickImages(){ Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT); i.addCategory(Intent.CATEGORY_OPENABLE); i.setType("image/*"); i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true); i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION); startActivityForResult(i,PICK_IMAGES); }
    private void pickAudio(){ Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT); i.addCategory(Intent.CATEGORY_OPENABLE); i.setType("audio/*"); i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION); startActivityForResult(i,PICK_AUDIO); }
    @Override protected void onActivityResult(int req,int res,Intent data){ super.onActivityResult(req,res,data); if(res!=RESULT_OK||data==null)return; if(req==PICK_IMAGES){ ArrayList<Uri> uris=new ArrayList<>(); if(data.getClipData()!=null){ for(int k=0;k<data.getClipData().getItemCount();k++) uris.add(data.getClipData().getItemAt(k).getUri()); } else if(data.getData()!=null) uris.add(data.getData()); for(Uri u:uris){ try{ getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){} project.clips.add(new TimelineClip(u.toString(),project.clips.size()+1,formulas.defaultFormula())); } store.save(project); refreshTimeline(); toast("Imported "+uris.size()+" image(s)"); } if(req==PICK_AUDIO && data.getData()!=null){ Uri u=data.getData(); try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){} project.audioUri=u.toString(); store.save(project); toast("Audio added"); } }
    private void durationDialog(){ final String[] opts={"1 sec","2 sec","3 sec","4 sec","5 sec","6 sec","7 sec","8 sec","Custom"}; new AlertDialog.Builder(this).setTitle("Apply Duration").setItems(opts,(d,which)->{ if(which==8) customDuration(); else applyDuration(which+1); }).show(); }
    private void customDuration(){ final EditText e=new EditText(this); e.setInputType(8194); e.setText("3"); new AlertDialog.Builder(this).setTitle("Custom seconds").setView(e).setPositiveButton("Apply",(di,w)->{ try{applyDuration(Float.parseFloat(e.getText().toString()));}catch(Exception ex){toast("Invalid duration");}}).show(); }
    private void applyDuration(float sec){ chooseScope("Duration",()->{if(selected>=0) project.clips.get(selected).durationSec=sec;},()->{for(TimelineClip c:project.clips)c.durationSec=sec;}); }
    private void formulaDialog(){ List<Formula> fs=formulas.all(); String[] names=new String[fs.size()]; for(int i=0;i<fs.size();i++) names[i]="Formula "+fs.get(i).id+" — "+fs.get(i).name; new AlertDialog.Builder(this).setTitle("FORMULA").setItems(names,(d,w)->{ Formula f=fs.get(w); chooseScope(f.name,()->{if(selected>=0) project.clips.get(selected).formula=formulas.byId(f.id);},()->{for(int i=0;i<project.clips.size();i++) project.clips.get(i).formula=f.id.equals("20")?formulas.randomFor(i):formulas.byId(f.id);}); }).show(); }
    private void transitionDialog(){ TransitionType[] vals=TransitionType.values(); String[] n=new String[vals.length]; for(int i=0;i<vals.length;i++) n[i]=vals[i].name().replace('_',' '); new AlertDialog.Builder(this).setTitle("TRANSITIONS").setItems(n,(d,w)-> chooseScope(n[w],()->{if(selected>=0)project.clips.get(selected).transition=vals[w];},()->{for(TimelineClip c:project.clips)c.transition=vals[w];})).show(); }
    private void effectDialog(){ EffectType[] vals=EffectType.values(); String[] n=new String[vals.length]; for(int i=0;i<vals.length;i++) n[i]=vals[i].name().replace('_',' '); new AlertDialog.Builder(this).setTitle("EFFECTS").setItems(n,(d,w)-> chooseScope(n[w],()->{if(selected>=0)project.clips.get(selected).effect=vals[w];},()->{for(TimelineClip c:project.clips)c.effect=vals[w];})).show(); }
    private void textDialog(){ final EditText e=new EditText(this); e.setText("AUTO EDIT"); new AlertDialog.Builder(this).setTitle("Add Text Overlay").setView(e).setPositiveButton("Add",(d,w)->{ TextOverlay t=new TextOverlay(); t.text=e.getText().toString(); t.endSec=project.totalDurationSec(); project.texts.add(t); store.save(project); preview.invalidate(); }).show(); }
    private void autoEditDialog(){ String[] modes={"Calm","Cinematic","Dynamic","Minimal","Random"}; new AlertDialog.Builder(this).setTitle("AUTO EDIT Mode").setItems(modes,(d,w)->{ for(int i=0;i<project.clips.size();i++){ TimelineClip c=project.clips.get(i); c.durationSec=w==2?2.2f:w==3?4f:3f; c.formula=w==4?formulas.randomFor(i):formulas.byId(w==0?"18":w==1?"17":w==2?"16":"14"); c.transition=TransitionType.CROSS_DISSOLVE; c.effect=w==3?EffectType.NONE:EffectType.CINEMATIC;} store.save(project); refreshTimeline(); }).show(); }
    private void chooseScope(String title, Runnable current, Runnable all){ new AlertDialog.Builder(this).setTitle("Apply "+title+" to").setItems(new String[]{"Current clip","All clips"},(d,w)->{ if(w==0) current.run(); else all.run(); store.save(project); refreshTimeline(); }).show(); }
    private void removeOrMoveDialog(int ix){ new AlertDialog.Builder(this).setTitle("Clip "+(ix+1)).setItems(new String[]{"Move left","Move right","Duplicate","Delete"},(d,w)->{ if(w==0&&ix>0) Collections.swap(project.clips,ix,ix-1); if(w==1&&ix<project.clips.size()-1) Collections.swap(project.clips,ix,ix+1); if(w==2){ TimelineClip c=project.clips.get(ix); TimelineClip n=new TimelineClip(c.uri,ix+2,c.formula); n.durationSec=c.durationSec;n.effect=c.effect;n.transition=c.transition;project.clips.add(ix+1,n);} if(w==3) project.clips.remove(ix); selected=-1; store.save(project); refreshTimeline(); }).show(); }
    private void exportDialog(){
        if(project.clips.isEmpty()){toast("Import images first");return;}
        ExportPreset[] presets=ExportPreset.values(); String[] labels=new String[presets.length];
        for(int i=0;i<presets.length;i++) labels[i]=presets[i].label+" • "+presets[i].width+"×"+presets[i].height+" • "+presets[i].useCase;
        new AlertDialog.Builder(this).setTitle("Export size / aspect ratio").setItems(labels,(d,w)->{
            if(presets[w]==ExportPreset.CUSTOM) customExportDialog(); else exportOptionsDialog(presets[w],presets[w].width,presets[w].height);
        }).show();
    }
    private void customExportDialog(){
        LinearLayout box=new LinearLayout(this); box.setOrientation(LinearLayout.VERTICAL); box.setPadding(32,16,32,0);
        EditText ew=new EditText(this); ew.setHint("Width"); ew.setInputType(2); ew.setText(String.valueOf(project.width));
        EditText eh=new EditText(this); eh.setHint("Height"); eh.setInputType(2); eh.setText(String.valueOf(project.height));
        box.addView(ew); box.addView(eh);
        new AlertDialog.Builder(this).setTitle("Custom export size").setView(box).setPositiveButton("Next",(d,w)->{
            try{ int cw=Integer.parseInt(ew.getText().toString()); int ch=Integer.parseInt(eh.getText().toString()); exportOptionsDialog(ExportPreset.CUSTOM,cw,ch); } catch(Exception e){ toast("Invalid size"); }
        }).show();
    }
    private void exportOptionsDialog(ExportPreset preset,int width,int height){
        String[] opts={"30 FPS • "+project.fitMode.label,"60 FPS • "+project.fitMode.label,"30 FPS • Toggle Fit/Fill","60 FPS • Toggle Fit/Fill"};
        new AlertDialog.Builder(this).setTitle("Export " + preset.label + " " + width + "×" + height).setItems(opts,(d,w)->{
            int fps=(w==1||w==3)?60:30; FitMode fit=(w>=2 ? (project.fitMode==FitMode.FILL?FitMode.FIT:FitMode.FILL) : project.fitMode);
            startExport(preset,width,height,fps,fit);
        }).show();
    }
    private void startExport(ExportPreset preset,int width,int height,int fps,FitMode fitMode){
        project.exportPreset=preset; project.width=width; project.height=height; project.fps=fps; project.fitMode=fitMode;
        if(project.width%2==1) project.width++; if(project.height%2==1) project.height++;
        Intent i=new Intent(this,ExportService.class); i.setAction(ExportService.ACTION_START); i.putExtra("w",project.width); i.putExtra("h",project.height); i.putExtra("fps",fps); i.putExtra("fitMode",fitMode.name());
        store.save(project); startService(i); status.setText("Export started • Gallery save: Movies/AutoEdit • "+project.width+"×"+project.height+" • "+fitMode.label);
    }
    private LinearLayout row(){ LinearLayout l=new LinearLayout(this); l.setOrientation(LinearLayout.HORIZONTAL); return l; }
    private TextView txt(String s,int sp,int color){ TextView v=new TextView(this); v.setText(s); v.setTextSize(sp); v.setTextColor(color); return v; }
    private void addBtn(LinearLayout parent,String label,View.OnClickListener l){ Button b=new Button(this); b.setText(label); b.setTextColor(Color.WHITE); GradientDrawable gd=new GradientDrawable(); gd.setColor(card); gd.setCornerRadius(22); gd.setStroke(1,0x3349A8FF); b.setBackground(gd); b.setAllCaps(false); b.setPadding(18,8,18,8); b.setOnClickListener(v->{ v.animate().scaleX(.96f).scaleY(.96f).setDuration(70).withEndAction(()->{ v.animate().scaleX(1f).scaleY(1f).setDuration(90).start(); l.onClick(v); }).start(); }); LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,-2); lp.setMargins(5,5,5,5); parent.addView(b,lp); }
    private void toast(String s){ Toast.makeText(this,s,Toast.LENGTH_LONG).show(); }
}
