package com.autoedit;

import android.app.*;import android.os.*;import android.content.*;import android.net.*;import android.util.Log;import android.view.*;import android.widget.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import java.util.*;
import com.autoedit.model.*;import com.autoedit.engine.*;import com.autoedit.project.*;import com.autoedit.export.*;import com.autoedit.ui.*;

public class MainActivity extends Activity {
    private static final int PICK_IMAGES=10, PICK_AUDIO=11; private static final String TAG="AutoEditMain";
    private EditProject project; private ProjectStore store; private FormulaEngine formulas;
    private LinearLayout root, timeline, panelHost; private TextView status, saveStatus, exportStage, exportPercent; private ProgressBar exportProgress;
    private PreviewView preview; private int selected=-1; private String screen="home"; private final ArrayDeque<String> undoStack=new ArrayDeque<>(), redoStack=new ArrayDeque<>();
    private ExportPreset draftPreset=ExportPreset.PORTRAIT_9_16; private int draftFps=30; private int draftQuality=1080; private FitMode draftFit=FitMode.FILL;
    private final Handler handler=new Handler(Looper.getMainLooper());
    private final Runnable autosave=new Runnable(){ public void run(){ saveProject(false); handler.postDelayed(this,30000); } };
    private final BroadcastReceiver exportReceiver=new BroadcastReceiver(){ public void onReceive(Context c,Intent i){ int p=i.getIntExtra("percent",0); String m=i.getStringExtra("message"); updateExportProgress(p,m); }};

    @Override public void onCreate(Bundle b){ super.onCreate(b); store=new ProjectStore(this); formulas=new FormulaEngine(); project=store.load(); draftPreset=project.exportPreset; draftFps=project.fps; draftFit=project.fitMode; showHome(); handler.postDelayed(autosave,30000); }
    @Override protected void onResume(){ super.onResume(); if(Build.VERSION.SDK_INT>=33) registerReceiver(exportReceiver,new IntentFilter(ExportService.ACTION_PROGRESS),RECEIVER_NOT_EXPORTED); else registerReceiver(exportReceiver,new IntentFilter(ExportService.ACTION_PROGRESS)); }
    @Override protected void onPause(){ super.onPause(); try{unregisterReceiver(exportReceiver);}catch(Exception ignored){} saveProject(false); }
    @Override protected void onDestroy(){ super.onDestroy(); handler.removeCallbacks(autosave); }
    @Override public void onBackPressed(){ if("editor".equals(screen)) showHome(); else if("create".equals(screen)||"export".equals(screen)||"settings".equals(screen)) showEditor(); else super.onBackPressed(); }

    private void base(){ root=new LinearLayout(this); root.setOrientation(LinearLayout.VERTICAL); root.setPadding(dp(16),dp(14),dp(16),dp(14)); root.setBackgroundColor(AeDesign.BG); applySystemInsets(root); setContentView(root); }
    private void applySystemInsets(View v){ v.setOnApplyWindowInsetsListener((view,insets)->{ int top=insets.getSystemWindowInsetTop(); int bottom=insets.getSystemWindowInsetBottom(); int left=insets.getSystemWindowInsetLeft(); int right=insets.getSystemWindowInsetRight(); view.setPadding(dp(16)+left,dp(14)+top,dp(16)+right,dp(14)+bottom); return insets; }); }

    private void showHome(){ screen="home"; base();
        LinearLayout header=row(); header.setGravity(Gravity.CENTER_VERTICAL); ImageView logo=new ImageView(this); logo.setImageResource(getResources().getIdentifier("ic_auto_edit","drawable",getPackageName())); header.addView(logo,new LinearLayout.LayoutParams(dp(58),dp(58)));
        LinearLayout titles=col(); titles.addView(label("Auto-Edit",30,AeDesign.TEXT,Typeface.BOLD)); titles.addView(label("Create. Edit. Export.",14,AeDesign.MUTED,Typeface.NORMAL)); header.addView(titles,new LinearLayout.LayoutParams(0,-2,1)); addSmallButton(header,"⚙",false,()->showSettings()); root.addView(header);
        Button create=AeDesign.button(this,"＋ Create Project",true); AeDesign.press(create,()->showCreateProject(false)); LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,dp(62)); cp.setMargins(0,dp(22),0,dp(20)); root.addView(create,cp);
        TextView recent=label("Recent Projects",20,AeDesign.TEXT,Typeface.BOLD); root.addView(recent);
        if(project.clips.isEmpty()) emptyState(); else projectCard(project);
    }

    private void emptyState(){ LinearLayout c=AeDesign.card(this); c.setGravity(Gravity.CENTER); TextView icon=label("▣▶",54,AeDesign.ACCENT,Typeface.BOLD); icon.setGravity(Gravity.CENTER); c.addView(icon); TextView a=label("No projects yet",22,AeDesign.TEXT,Typeface.BOLD); a.setGravity(Gravity.CENTER); c.addView(a); TextView b=label("Create your first video from images and make it move.",14,AeDesign.MUTED,Typeface.NORMAL); b.setGravity(Gravity.CENTER); c.addView(b); LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,0,1); lp.setMargins(0,dp(20),0,0); root.addView(c,lp); }

    private void projectCard(EditProject p){ LinearLayout card=AeDesign.card(this); card.setPadding(dp(18),dp(18),dp(18),dp(18));
        LinearLayout top=row(); TextView thumb=label("▶",36,AeDesign.ACCENT,Typeface.BOLD); thumb.setGravity(Gravity.CENTER); thumb.setBackground(AeDesign.gradient(0xff102D4A,0xff172044,dp(18))); top.addView(thumb,new LinearLayout.LayoutParams(dp(86),dp(72)));
        LinearLayout info=col(); info.setPadding(dp(14),0,0,0); info.addView(label(p.name,19,AeDesign.TEXT,Typeface.BOLD)); info.addView(label(p.clips.size()+" clips • "+fmt(p.totalDurationSec())+" • "+p.width+"×"+p.height+" • "+p.fitMode.label,13,AeDesign.MUTED,Typeface.NORMAL)); info.addView(label("Last edited: just now • Auto Saved",12,0xff6f8ca4,Typeface.NORMAL)); top.addView(info,new LinearLayout.LayoutParams(0,-2,1)); addSmallButton(top,"⋮",false,()->projectMenu()); card.addView(top);
        Button cont=AeDesign.button(this,"Continue Editing",true); AeDesign.press(cont,()->showEditor()); LinearLayout.LayoutParams lpbtn=new LinearLayout.LayoutParams(-1,dp(52)); lpbtn.setMargins(0,dp(16),0,0); card.addView(cont,lpbtn); LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2); lp.setMargins(0,dp(14),0,0); root.addView(card,lp); }

    private void projectMenu(){ String[] ops={"Rename","Duplicate","Delete","Project Settings"}; new AlertDialog.Builder(this).setTitle("Project").setItems(ops,(d,w)->{ if(w==0) renameProject(); if(w==1){ project.name=project.name+" Copy"; saveProject(true); showHome(); } if(w==2){ project=new EditProject(); saveProject(true); showHome(); } if(w==3) showCreateProject(true); }).show(); }
    private void renameProject(){ final EditText e=new EditText(this); e.setText(project.name); new AlertDialog.Builder(this).setTitle("Rename project").setView(e).setPositiveButton("Save",(d,w)->{ project.name=e.getText().toString(); saveProject(true); showHome(); }).show(); }

    private void showCreateProject(boolean settingsOnly){ screen="create"; base(); addHeader("Create Project", "Setup canvas, resolution and frame rate", ()->showHome());
        root.addView(label("Aspect Ratio",18,AeDesign.TEXT,Typeface.BOLD)); LinearLayout ratios=rowWrap(); addRatio(ratios,ExportPreset.PORTRAIT_9_16,"9:16\nReels / Shorts"); addRatio(ratios,ExportPreset.LANDSCAPE_16_9,"16:9\nYouTube"); addRatio(ratios,ExportPreset.SQUARE_1_1,"1:1\nSquare"); addRatio(ratios,ExportPreset.PORTRAIT_4_5,"4:5\nInstagram"); addRatio(ratios,ExportPreset.CLASSIC_4_3,"4:3\nClassic"); root.addView(ratios);
        root.addView(label("Resolution",18,AeDesign.TEXT,Typeface.BOLD)); LinearLayout res=row(); addChoice(res,"720p",draftQuality==720,()->draftQuality=720); addChoice(res,"1080p",draftQuality==1080,()->draftQuality=1080); addChoice(res,"4K",draftQuality==2160,()->draftQuality=2160); root.addView(res);
        root.addView(label("FPS",18,AeDesign.TEXT,Typeface.BOLD)); LinearLayout fps=row(); addChoice(fps,"24 FPS",draftFps==24,()->draftFps=24); addChoice(fps,"30 FPS",draftFps==30,()->draftFps=30); addChoice(fps,"60 FPS",draftFps==60,()->draftFps=60); root.addView(fps);
        Button create=AeDesign.button(this,settingsOnly?"Apply Settings":"Create Project",true); AeDesign.press(create,()->{ if(!settingsOnly) project=new EditProject(); applyDraftToProject(); saveProject(true); showEditor(); }); LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(58)); lp.setMargins(0,dp(20),0,0); root.addView(create,lp); }

    private void addRatio(LinearLayout parent, ExportPreset preset, String text){ TextView v=label((draftPreset==preset?"✓ ":"")+text,14,AeDesign.TEXT,Typeface.BOLD); v.setGravity(Gravity.CENTER); v.setBackground(AeDesign.bg(draftPreset==preset?0xff102D4A:AeDesign.SURFACE,dp(20),draftPreset==preset?AeDesign.ACCENT:AeDesign.STROKE,2)); AeDesign.press(v,()->{ draftPreset=preset; showCreateProject(false); }); LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(dp(106),dp(92)); lp.setMargins(dp(5),dp(8),dp(5),dp(8)); parent.addView(v,lp); }
    private void applyDraftToProject(){ int h=draftQuality; int w=Math.round(h*draftPreset.width/(float)draftPreset.height); if(draftPreset==ExportPreset.PORTRAIT_9_16){w=1080;h=draftQuality==2160?3840:1920;} else if(draftPreset==ExportPreset.SQUARE_1_1){w=h=draftQuality;} else if(draftPreset==ExportPreset.PORTRAIT_4_5){w=1080;h=1350;} else if(draftPreset==ExportPreset.CLASSIC_4_3){w=1440;h=1080;} project.exportPreset=draftPreset; project.width=w; project.height=h; project.fps=draftFps; project.fitMode=draftFit; }

    private void showEditor(){ screen="editor"; base();
        LinearLayout header=row(); header.setGravity(Gravity.CENTER_VERTICAL); addSmallButton(header,"‹",false,()->showHome()); LinearLayout title=col(); title.addView(label(project.name,18,AeDesign.TEXT,Typeface.BOLD)); saveStatus=label("Auto Saved",12,0xff7ce0a2,Typeface.NORMAL); title.addView(saveStatus); header.addView(title,new LinearLayout.LayoutParams(0,-2,1)); addSmallButton(header,"Undo",false,()->undo()); addSmallButton(header,"Redo",false,()->redo()); addSmallButton(header,"EXPORT",true,()->showExportScreen()); root.addView(header);
        FrameLayout monitor=new FrameLayout(this); monitor.setPadding(dp(10),dp(12),dp(10),dp(12)); monitor.setBackground(AeDesign.bg(0xff03070d,dp(24),0x22334a68,1)); preview=new PreviewView(this); preview.project=project; monitor.addView(preview, previewParams()); LinearLayout.LayoutParams mlp=new LinearLayout.LayoutParams(-1,0,3); mlp.setMargins(0,dp(12),0,dp(8)); root.addView(monitor,mlp);
        LinearLayout player=row(); player.setGravity(Gravity.CENTER_VERTICAL); addSmallButton(player,"▶ / Ⅱ",false,()->{ if(preview.playing) preview.pause(); else preview.play(); }); player.addView(label("  00:00 / "+fmt(project.totalDurationSec())+"   FPS "+project.fps+"   "+project.fitMode.label,13,AeDesign.MUTED,Typeface.NORMAL)); root.addView(player);
        HorizontalScrollView toolsScroll=new HorizontalScrollView(this); LinearLayout tools=row(); toolsScroll.addView(tools); addTool(tools,"＋ IMAGES",()->pickImages()); addTool(tools,"Motion",()->motionPanel()); addTool(tools,"Formula",()->formulaBatchPanel()); addTool(tools,"Transition",()->transitionPanel()); addTool(tools,"Text",()->textStudio()); addTool(tools,"Audio",()->audioStudio()); addTool(tools,"Speed",()->speedPanel()); addTool(tools,"Filters",()->filtersPanel()); addTool(tools,"Effects",()->effectsPanel()); addTool(tools,"Adjust",()->adjustPanel()); addTool(tools,"Canvas",()->canvasPanel()); addTool(tools,"Stickers",()->stickersPanel()); addTool(tools,"Auto Edit",()->autoEditPanel()); root.addView(toolsScroll);
        buildTimeline(); panelHost=col(); root.addView(panelHost,new LinearLayout.LayoutParams(-1,dp(142))); showClipPanel(); }

    private FrameLayout.LayoutParams previewParams(){ float r=project.width/(float)Math.max(1,project.height); int sw=getResources().getDisplayMetrics().widthPixels-dp(72); int h=(int)(sw/r); int max=dp(330); if(h>max){h=max; sw=(int)(h*r);} FrameLayout.LayoutParams lp=new FrameLayout.LayoutParams(sw,h,Gravity.CENTER); return lp; }

    private void buildTimeline(){ LinearLayout box=AeDesign.card(this); box.setPadding(dp(10),dp(8),dp(10),dp(8)); TextView ruler=label("Video Track      │ Playhead      Zoom −  +      Snap ON",12,AeDesign.MUTED,Typeface.NORMAL); box.addView(ruler); HorizontalScrollView hsv=new HorizontalScrollView(this); timeline=row(); hsv.addView(timeline); box.addView(hsv,new LinearLayout.LayoutParams(-1,dp(94))); LinearLayout tracks=col(); tracks.addView(trackLabel("Audio Track", project.audioUri==null?"No audio":"Waveform linked", true)); tracks.addView(trackLabel("Text Track", project.texts.size()+" text block(s)", false)); tracks.addView(trackLabel("Overlay Track", "Stickers / PNG overlays coming soon", false)); box.addView(tracks); root.addView(box,new LinearLayout.LayoutParams(-1,dp(210))); refreshTimeline(); }
    private TextView trackLabel(String a,String b,boolean wave){ TextView v=label(a+"  •  "+b,12,wave?AeDesign.ACCENT:AeDesign.MUTED,Typeface.NORMAL); v.setPadding(dp(8),dp(3),dp(8),dp(3)); return v; }
    private void refreshTimeline(){ if(timeline==null)return; timeline.removeAllViews(); project.renumber(); for(int i=0;i<project.clips.size();i++){ TimelineClip c=project.clips.get(i); TextView v=label("⋮⋮\nClip "+String.format(Locale.US,"%02d",c.index)+"\n"+c.durationSec+"s",12,AeDesign.TEXT,Typeface.BOLD); v.setGravity(Gravity.CENTER); v.setBackground(AeDesign.bg(i==selected?0xff12395c:AeDesign.SURFACE_2,dp(16),i==selected?AeDesign.ACCENT:AeDesign.STROKE,2)); final int ix=i; AeDesign.press(v,()->{ selected=ix; if(preview!=null) preview.seekTo(project.clips.get(ix).startTimeMsIn(project)/1000f); refreshTimeline(); showClipPanel(); }); v.setOnLongClickListener(x->{ removeOrMoveDialog(ix); return true; }); LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(dp(54 + Math.round(c.durationSec)*12),dp(84)); lp.setMargins(dp(4),dp(4),dp(4),dp(4)); timeline.addView(v,lp); } if(status!=null) status.setText(project.clips.size()+" clips • "+fmt(project.totalDurationSec())); if(preview!=null) preview.invalidate(); }

    private void showClipPanel(){ if(panelHost==null)return; panelHost.removeAllViews(); if(selected<0 || selected>=project.clips.size()){ panelHost.addView(label("Select a clip to open Trim, Split, Crop, Animation, Filters and Adjust controls.",13,AeDesign.MUTED,Typeface.NORMAL)); return; } TimelineClip c=project.clips.get(selected); panelHost.addView(label("Clip "+c.index+" editing",16,AeDesign.TEXT,Typeface.BOLD)); addDurationControls(c); LinearLayout actions=rowWrap(); addAction(actions,"Trim",()->durationDialog()); addAction(actions,"Split",()->toast("Split is coming soon for image clips")); addAction(actions,"Delete",()->{ pushUndo(); project.clips.remove(selected); selected=-1; saveProject(true); showEditor(); }); addAction(actions,"Duplicate",()->duplicateClip()); addAction(actions,"Crop",()->canvasPanel()); addAction(actions,"Rotate",()->toast("Rotation keyframe panel coming soon")); addAction(actions,"Animation",()->motionPanel()); addAction(actions,"Filters",()->filtersPanel()); panelHost.addView(actions); }

    private void addDurationControls(TimelineClip clip){
        panelHost.addView(label("Duration",13,AeDesign.MUTED,Typeface.BOLD));
        LinearLayout durations=row(); int[] vals={3,4,5,6,7,8};
        for(int val: vals){ final int sec=val; TextView v=label(sec+"s",13,AeDesign.TEXT,Typeface.BOLD); v.setGravity(Gravity.CENTER); boolean on=Math.round(clip.durationSec)==sec; v.setBackground(AeDesign.bg(on?0xff12395c:AeDesign.SURFACE_2,dp(14),on?AeDesign.ACCENT:AeDesign.STROKE,2)); AeDesign.press(v,()->{ pushUndo(); clip.setDurationMs(sec*1000L); saveProject(true); refreshTimeline(); showClipPanel(); }); LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(40),1); lp.setMargins(dp(3),dp(4),dp(3),dp(6)); durations.addView(v,lp); }
        panelHost.addView(durations);
        LinearLayout batch=row(); addAction(batch,"Apply this duration to ALL",()->applyDurationToAll(Math.round(clip.durationSec))); addAction(batch,"Preview from clip",()->{ if(preview!=null) preview.seekTo(clip.startTimeMsIn(project)/1000f); }); panelHost.addView(batch);
    }

    private void showMediaPanel(){ showPanel("Media Picker", new String[]{"Images: open system multi-select", "Videos: coming soon", "Recent/Albums: use device picker", "Selected count appears after import"}, new Runnable[]{()->pickImages(),()->toast("Video import coming soon"),()->pickImages(),()->toast(project.clips.size()+" clips selected")}); }
    private void motionPanel(){ showPanel("Motion", new String[]{"Zoom In", "Zoom Out", "Pan Left", "Pan Right", "Pan Up", "Pan Down", "Slow Zoom", "No Motion"}, new Runnable[]{()->applyFormula("06"),()->applyFormula("07"),()->applyFormula("02"),()->applyFormula("04"),()->applyFormula("05"),()->applyFormula("01"),()->applyFormula("14"),()->applyFormula("00")}); }
    private void formulaBatchPanel(){
        showPanel("Motion Formula",
                new String[]{"Story Zoom • Apply to All", "Documentary • Apply to All", "Cinematic • Apply to All", "Pan Mix • Apply to All", "Slow Motion • Apply to All", "Remove Formula from All"},
                new Runnable[]{()->applyFormulaSequenceToAll("story"),()->applyFormulaSequenceToAll("documentary"),()->applyFormulaSequenceToAll("cinematic"),()->applyFormulaSequenceToAll("pan"),()->applyFormulaSequenceToAll("slow"),()->applyFormulaSequenceToAll("none")});
    }

    private void motionPresets(){ List<Formula> fs=formulas.all(); String[] names=new String[Math.min(13,fs.size())]; Runnable[] runs=new Runnable[names.length]; for(int i=0;i<names.length;i++){ Formula f=fs.get(i+5<fs.size()?i+5:i); names[i]="▶ "+f.name; runs[i]=()->{}; final String id=f.id; runs[i]=()->applyFormula(id); } showPanel("Motion Presets",names,runs); }
    private void transitionPanel(){ TransitionType[] vals={TransitionType.FADE,TransitionType.CROSS_DISSOLVE,TransitionType.SLIDE_LEFT,TransitionType.SLIDE_RIGHT,TransitionType.SLIDE_UP,TransitionType.SLIDE_DOWN,TransitionType.ZOOM,TransitionType.FLASH,TransitionType.CINEMATIC_BLUR}; String[] n=new String[vals.length]; Runnable[] r=new Runnable[vals.length]; for(int i=0;i<vals.length;i++){ n[i]="▧ "+vals[i].name().replace('_',' '); final TransitionType t=vals[i]; r[i]=()->applyTransition(t); } showPanel("Transition Browser",n,r); }
    private void textStudio(){ showPanel("Text Studio", new String[]{"Title preset", "Subtitle preset", "Caption preset", "YouTube preset", "Shorts preset", "Documentary preset", "End Card"}, new Runnable[]{()->addText("Title"),()->addText("Subtitle"),()->addText("Caption"),()->addText("YouTube Title"),()->addText("Shorts Caption"),()->addText("Documentary Lower Third"),()->addText("Thanks for watching")}); }
    private void audioStudio(){ showPanel("Audio Studio", new String[]{"Import music/audio", "Voice-over recording: coming soon", "Volume 100%", "Fade in/out: coming soon", "Mute audio"}, new Runnable[]{()->pickAudio(),()->toast("Voice-over coming soon"),()->toast("Volume controls coming soon"),()->toast("Fade controls coming soon"),()->{ pushUndo(); project.audioUri=null; saveProject(true); toast("Audio muted/deleted"); }}); }
    private void speedPanel(){ showPanel("Speed", new String[]{"0.25x coming soon","0.5x coming soon","0.75x coming soon","1x default","1.25x coming soon","1.5x coming soon","2x coming soon","4x coming soon"}, new Runnable[]{()->toast("Coming soon"),()->toast("Coming soon"),()->toast("Coming soon"),()->toast("Default speed"),()->toast("Coming soon"),()->toast("Coming soon"),()->toast("Coming soon"),()->toast("Coming soon")}); }
    private void filtersPanel(){ showPanel("Filters", new String[]{"Cinematic","Warm","Cool","Vintage","Film","B&W","Dramatic","Portrait","HDR-style"}, new Runnable[]{()->applyEffect(EffectType.CINEMATIC),()->applyEffect(EffectType.TEMPERATURE),()->applyEffect(EffectType.SOFT_FOCUS),()->applyEffect(EffectType.VINTAGE),()->applyEffect(EffectType.FILM),()->applyEffect(EffectType.BLACK_WHITE),()->applyEffect(EffectType.CONTRAST),()->applyEffect(EffectType.DREAM),()->applyEffect(EffectType.SHARPEN)}); }
    private void effectsPanel(){ showPanel("Effects", new String[]{"Glow","Flash","Vignette","Blur","Motion Blur","Grain","Vintage","Cinematic","Reset"}, new Runnable[]{()->applyEffect(EffectType.GLOW),()->applyTransition(TransitionType.FLASH),()->applyEffect(EffectType.VIGNETTE),()->applyEffect(EffectType.BLUR),()->applyEffect(EffectType.MOTION_BLUR),()->applyEffect(EffectType.FILM_GRAIN),()->applyEffect(EffectType.VINTAGE),()->applyEffect(EffectType.CINEMATIC),()->applyEffect(EffectType.NONE)}); }
    private void adjustPanel(){ showPanel("Color Adjust", new String[]{"Brightness","Contrast","Saturation","Exposure","Temperature","Highlights","Shadows","Sharpen","Reset"}, new Runnable[]{()->applyEffect(EffectType.BRIGHTNESS),()->applyEffect(EffectType.CONTRAST),()->applyEffect(EffectType.SATURATION),()->applyEffect(EffectType.EXPOSURE),()->applyEffect(EffectType.TEMPERATURE),()->applyEffect(EffectType.HIGHLIGHTS),()->applyEffect(EffectType.SHADOWS),()->applyEffect(EffectType.SHARPEN),()->applyEffect(EffectType.NONE)}); }
    private void canvasPanel(){ showPanel("Canvas", new String[]{"Fit", "Fill", "16:9", "9:16", "1:1", "4:5", "Rotate/Flip coming soon"}, new Runnable[]{()->{project.fitMode=FitMode.FIT;saveProject(true);},()->{project.fitMode=FitMode.FILL;saveProject(true);},()->setPreset(ExportPreset.LANDSCAPE_16_9),()->setPreset(ExportPreset.PORTRAIT_9_16),()->setPreset(ExportPreset.SQUARE_1_1),()->setPreset(ExportPreset.PORTRAIT_4_5),()->toast("Rotate/Flip coming soon")}); }
    private void stickersPanel(){ showPanel("Stickers / Overlays", new String[]{"Emoji coming soon","Shapes coming soon","Arrows coming soon","Frames coming soon","Import PNG coming soon"}, new Runnable[]{()->toast("Coming soon"),()->toast("Coming soon"),()->toast("Coming soon"),()->toast("Coming soon"),()->toast("PNG overlay import coming soon")}); }
    private void autoEditPanel(){ showPanel("Auto Edit", new String[]{"Cinematic","Fast","Smooth","Shorts","Documentary","Vlog"}, new Runnable[]{()->autoEdit(1),()->autoEdit(2),()->autoEdit(0),()->autoEdit(3),()->autoEdit(4),()->autoEdit(5)}); }

    private void showPanel(String title,String[] items,Runnable[] actions){ if(panelHost==null)return; panelHost.removeAllViews(); panelHost.addView(label(title,16,AeDesign.TEXT,Typeface.BOLD)); LinearLayout grid=rowWrap(); for(int i=0;i<items.length;i++){ final Runnable r=actions[i]; addAction(grid,items[i],()->{ r.run(); if(preview!=null)preview.invalidate(); }); } panelHost.addView(grid); }
    private void addText(String s){ pushUndo(); TextOverlay t=new TextOverlay(); t.text=s; t.endSec=Math.max(3,project.totalDurationSec()); project.texts.add(t); saveProject(true); toast("Text added: "+s); }
    private void applyFormula(String id){ pushUndo(); if(selected>=0) project.clips.get(selected).formula=formulas.byId(id); else for(int i=0;i<project.clips.size();i++) project.clips.get(i).formula=formulas.byId(id); saveProject(true); refreshTimeline(); }
    private void applyDurationToAll(int sec){
        pushUndo();
        for(TimelineClip c:project.clips) c.setDurationMs(sec*1000L);
        saveProject(true); refreshTimeline(); showClipPanel(); toast("All images set to "+sec+"s");
    }

    private void applyFormulaSequenceToAll(String mode){
        pushUndo();
        String[] story={"06","08","07","09"};
        String[] doc={"14","04","15","02"};
        String[] cine={"06","05","07","01"};
        String[] pan={"04","02","01","05"};
        String[] slow={"18","14","18","15"};
        String[] use=story; if("documentary".equals(mode)) use=doc; else if("cinematic".equals(mode)) use=cine; else if("pan".equals(mode)) use=pan; else if("slow".equals(mode)) use=slow;
        for(int i=0;i<project.clips.size();i++){ project.clips.get(i).formula=formulas.byId("none".equals(mode)?"00":use[i%use.length]); }
        saveProject(true); refreshTimeline(); if(preview!=null)preview.invalidate(); toast("Motion formula applied to "+project.clips.size()+" clips");
    }

    private void applyTransition(TransitionType t){ pushUndo(); if(selected>=0) project.clips.get(selected).transition=t; else for(TimelineClip c:project.clips)c.transition=t; saveProject(true); toast("Transition applied: "+t.name()); }
    private void applyEffect(EffectType e){ pushUndo(); if(selected>=0) project.clips.get(selected).effect=e; else for(TimelineClip c:project.clips)c.effect=e; saveProject(true); toast("Effect applied: "+e.name()); }
    private void duplicateClip(){ if(selected<0)return; pushUndo(); TimelineClip c=project.clips.get(selected); TimelineClip n=new TimelineClip(c.uri,selected+2,c.formula); n.setDurationMs(c.durationMs); n.effect=c.effect; n.transition=c.transition; n.transitionDurationSec=c.transitionDurationSec; project.clips.add(selected+1,n); saveProject(true); refreshTimeline(); }
    private void autoEdit(int mode){ pushUndo(); for(int i=0;i<project.clips.size();i++){ TimelineClip c=project.clips.get(i); c.setDurationSeconds(mode==2?3f:mode==3?4f:5f); c.formula=mode==2?formulas.byId("16"):mode==3?formulas.byId("14"):mode==4?formulas.byId("17"):formulas.randomFor(i); c.transition=TransitionType.CROSS_DISSOLVE; c.effect=mode==0?EffectType.SOFT_FOCUS:EffectType.CINEMATIC; } saveProject(true); refreshTimeline(); toast("Auto Edit generated"); }
    private void setPreset(ExportPreset p){ pushUndo(); draftPreset=p; project.applyExportPreset(p); saveProject(true); toast("Canvas set: "+p.label); }

    private void showExportScreen(){ screen="export"; base(); addHeader("Export Video", "Existing production export system", ()->showEditor());
        LinearLayout summary=AeDesign.card(this); summary.addView(label("Project",12,AeDesign.MUTED,Typeface.NORMAL)); summary.addView(label(project.name,20,AeDesign.TEXT,Typeface.BOLD)); summary.addView(label("Duration: "+fmt(project.totalDurationSec())+" • Clips: "+project.clips.size(),14,AeDesign.MUTED,Typeface.NORMAL)); root.addView(summary);
        root.addView(label("Aspect Ratio / Resolution",18,AeDesign.TEXT,Typeface.BOLD)); LinearLayout presets=rowWrap(); for(ExportPreset p:ExportPreset.values()) addExportPreset(presets,p); root.addView(presets);
        root.addView(label("FPS",18,AeDesign.TEXT,Typeface.BOLD)); LinearLayout fps=row(); addChoice(fps,"24",draftFps==24,()->{draftFps=24;showExportScreen();}); addChoice(fps,"30",draftFps==30,()->{draftFps=30;showExportScreen();}); addChoice(fps,"60",draftFps==60,()->{draftFps=60;showExportScreen();}); root.addView(fps);
        LinearLayout fit=row(); addChoice(fit,"Fill Crop",draftFit==FitMode.FILL,()->{draftFit=FitMode.FILL;showExportScreen();}); addChoice(fit,"Fit Letterbox",draftFit==FitMode.FIT,()->{draftFit=FitMode.FIT;showExportScreen();}); root.addView(fit);
        exportProgress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal); exportProgress.setMax(100); exportProgress.setProgress(0); root.addView(exportProgress,new LinearLayout.LayoutParams(-1,dp(12))); exportPercent=label("0%",24,AeDesign.ACCENT,Typeface.BOLD); exportStage=label("Ready to export. Output will use the existing Gallery save implementation.",14,AeDesign.MUTED,Typeface.NORMAL); root.addView(exportPercent); root.addView(exportStage);
        Button go=AeDesign.button(this,"EXPORT VIDEO",true); AeDesign.press(go,()->startExistingExport()); LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(60)); lp.setMargins(0,dp(18),0,0); root.addView(go,lp); }
    private void addExportPreset(LinearLayout parent,ExportPreset p){ TextView v=label((draftPreset==p?"✓ ":"")+p.label+"\n"+p.width+"×"+p.height,13,AeDesign.TEXT,Typeface.BOLD); v.setGravity(Gravity.CENTER); v.setBackground(AeDesign.bg(draftPreset==p?0xff102D4A:AeDesign.SURFACE,dp(18),draftPreset==p?AeDesign.ACCENT:AeDesign.STROKE,2)); AeDesign.press(v,()->{draftPreset=p;showExportScreen();}); LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(dp(112),dp(78)); lp.setMargins(dp(4),dp(7),dp(4),dp(7)); parent.addView(v,lp); }
    private void startExistingExport(){ if(project.clips.isEmpty()){ toast("Import images first"); return; } int width=draftPreset.width,height=draftPreset.height; if(draftPreset==ExportPreset.CUSTOM){ width=project.width; height=project.height; } project.exportPreset=draftPreset; project.width=width; project.height=height; project.fps=draftFps; project.fitMode=draftFit; if(project.width%2==1)project.width++; if(project.height%2==1)project.height++; Intent i=new Intent(this,ExportService.class); i.setAction(ExportService.ACTION_START); i.putExtra("w",project.width); i.putExtra("h",project.height); i.putExtra("fps",project.fps); i.putExtra("fitMode",project.fitMode.name()); saveProject(true); startService(i); updateExportProgress(1,"Preparing..."); }
    private void updateExportProgress(int p,String m){ if(status!=null) status.setText(p<0?"Export failed: "+m:"Export "+p+"% • "+m); if(exportProgress!=null){ exportProgress.setProgress(Math.max(0,p)); exportPercent.setText(p<0?"Failed":p+"%"); exportStage.setText(stage(p,m)); if(p==100) exportStage.setText("✓ Export Complete • "+m+"\nShare / Open in Gallery from your Gallery app."); } }
    private String stage(int p,String m){ if(p<0)return m; if(p<10)return "Preparing... "+m; if(p<45)return "Processing... "+m; if(p<85)return "Encoding... "+m; if(p<100)return "Finalizing and saving to Gallery... "+m; return m; }

    private void pickImages(){ try{ Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT); i.addCategory(Intent.CATEGORY_OPENABLE); i.setType("image/*"); i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true); i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION); startActivityForResult(i,PICK_IMAGES); }catch(Exception e){ Log.e(TAG,"Image picker failed",e); toast("Could not open image picker"); } }
    private void pickAudio(){ Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT); i.addCategory(Intent.CATEGORY_OPENABLE); i.setType("audio/*"); i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION); startActivityForResult(i,PICK_AUDIO); }
    @Override protected void onActivityResult(int req,int res,Intent data){ super.onActivityResult(req,res,data); if(res!=RESULT_OK||data==null)return; if(req==PICK_IMAGES){ ArrayList<Uri> uris=new ArrayList<>(); if(data.getClipData()!=null){ for(int k=0;k<data.getClipData().getItemCount();k++) uris.add(data.getClipData().getItemAt(k).getUri()); } else if(data.getData()!=null) uris.add(data.getData()); if(!uris.isEmpty()) pushUndo(); for(Uri u:uris){ try{ getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){} try{ TimelineClip clip=new TimelineClip(u.toString(),project.clips.size()+1,formulas.defaultFormula()); clip.setDurationMs(5000L); project.clips.add(clip); }catch(Exception e){ Log.e(TAG,"Image clip creation failed: "+u,e); toast("Skipped one image"); } } saveProject(true); showEditor(); toast("Imported "+uris.size()+" image(s)"); } if(req==PICK_AUDIO && data.getData()!=null){ pushUndo(); Uri u=data.getData(); try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){} project.audioUri=u.toString(); saveProject(true); if("editor".equals(screen))showEditor(); toast("Audio added"); } }
    private void durationDialog(){ final int[] secs={3,4,5,6,7,8}; final String[] opts={"3 sec","4 sec","5 sec","6 sec","7 sec","8 sec"}; new AlertDialog.Builder(this).setTitle("Apply Image Duration").setItems(opts,(d,which)-> applyDuration(secs[which])).show(); }
    private void applyDuration(float sec){ pushUndo(); if(selected>=0) project.clips.get(selected).setDurationSeconds(sec); else for(TimelineClip c:project.clips)c.setDurationSeconds(sec); saveProject(true); refreshTimeline(); }
    private void formulaDialog(){ List<Formula> fs=formulas.all(); String[] names=new String[fs.size()]; for(int i=0;i<fs.size();i++) names[i]="Formula "+fs.get(i).id+" — "+fs.get(i).name; new AlertDialog.Builder(this).setTitle("FORMULA").setItems(names,(d,w)->applyFormula(fs.get(w).id)).show(); }
    private void removeOrMoveDialog(int ix){ new AlertDialog.Builder(this).setTitle("Clip "+(ix+1)).setItems(new String[]{"Move left","Move right","Duplicate","Delete"},(d,w)->{ if(w==2){ selected=ix; duplicateClip(); return;} pushUndo(); if(w==0&&ix>0) Collections.swap(project.clips,ix,ix-1); if(w==1&&ix<project.clips.size()-1) Collections.swap(project.clips,ix,ix+1); if(w==3) project.clips.remove(ix); selected=-1; saveProject(true); refreshTimeline(); showClipPanel(); }).show(); }
    private void showSettings(){ screen="settings"; base(); addHeader("Settings", "Editor • Playback • Export • Storage • About", ()->showHome()); showPanelIntoRoot("Editor", new String[]{"Default aspect ratio: "+draftPreset.label,"Default FPS: "+draftFps,"Auto-save: ON","Timeline snapping: ON"}); showPanelIntoRoot("Playback", new String[]{"Preview quality: Optimized","Preview FPS: "+project.fps}); showPanelIntoRoot("Export", new String[]{"Default resolution: "+project.width+"×"+project.height,"Default quality: High"}); showPanelIntoRoot("Storage", new String[]{"Export location: Movies/AutoEdit","Clear temporary files: use Android app storage settings"}); showPanelIntoRoot("About", new String[]{"Auto-Edit","Privacy: offline-first media stays on device","Version 1.0.5"}); }

    private void pushUndo(){
        try{ undoStack.push(store.toJsonString(project)); redoStack.clear(); while(undoStack.size()>40) undoStack.removeLast(); }catch(Exception e){ Log.e(TAG,"Undo snapshot failed",e); }
    }
    private void undo(){
        if(undoStack.isEmpty()){ toast("Nothing to undo"); return; }
        try{ redoStack.push(store.toJsonString(project)); project=store.fromJsonString(undoStack.pop()); selected=-1; saveProject(false); if("editor".equals(screen)) showEditor(); else if("home".equals(screen)) showHome(); else if("export".equals(screen)) showExportScreen(); toast("Undo"); }catch(Exception e){ Log.e(TAG,"Undo failed",e); toast("Undo failed"); }
    }
    private void redo(){
        if(redoStack.isEmpty()){ toast("Nothing to redo"); return; }
        try{ undoStack.push(store.toJsonString(project)); project=store.fromJsonString(redoStack.pop()); selected=-1; saveProject(false); if("editor".equals(screen)) showEditor(); else if("home".equals(screen)) showHome(); else if("export".equals(screen)) showExportScreen(); toast("Redo"); }catch(Exception e){ Log.e(TAG,"Redo failed",e); toast("Redo failed"); }
    }

    private void addHeader(String title,String subtitle,Runnable back){ LinearLayout h=row(); h.setGravity(Gravity.CENTER_VERTICAL); addSmallButton(h,"‹",false,back); LinearLayout t=col(); t.addView(label(title,24,AeDesign.TEXT,Typeface.BOLD)); t.addView(label(subtitle,13,AeDesign.MUTED,Typeface.NORMAL)); h.addView(t,new LinearLayout.LayoutParams(0,-2,1)); root.addView(h); }
    private void addTool(LinearLayout p,String s,Runnable r){ addSmallButton(p,s,false,r); }
    private void addAction(LinearLayout p,String s,Runnable r){ TextView v=label(s,12,AeDesign.TEXT,Typeface.BOLD); v.setGravity(Gravity.CENTER); v.setBackground(AeDesign.bg(AeDesign.SURFACE_2,dp(18),AeDesign.STROKE,1)); AeDesign.press(v,r); LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(dp(104),dp(48)); lp.setMargins(dp(4),dp(4),dp(4),dp(4)); p.addView(v,lp); }
    private void addChoice(LinearLayout p,String s,boolean selected,Runnable r){ TextView v=label((selected?"✓ ":"")+s,14,AeDesign.TEXT,Typeface.BOLD); v.setGravity(Gravity.CENTER); v.setBackground(AeDesign.bg(selected?0xff102D4A:AeDesign.SURFACE,dp(20),selected?AeDesign.ACCENT:AeDesign.STROKE,2)); AeDesign.press(v,r); LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(52),1); lp.setMargins(dp(4),dp(8),dp(4),dp(8)); p.addView(v,lp); }
    private void addSmallButton(LinearLayout p,String s,boolean primary,Runnable r){ Button b=AeDesign.button(this,s,primary); AeDesign.press(b,r); LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,dp(48)); lp.setMargins(dp(4),dp(4),dp(4),dp(4)); p.addView(b,lp); }
    private void showPanelIntoRoot(String title,String[] rows){ LinearLayout c=AeDesign.card(this); c.addView(label(title,16,AeDesign.TEXT,Typeface.BOLD)); for(String s:rows)c.addView(label("• "+s,13,AeDesign.MUTED,Typeface.NORMAL)); LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2); lp.setMargins(0,dp(8),0,dp(4)); root.addView(c,lp); }
    private LinearLayout row(){ LinearLayout l=new LinearLayout(this); l.setOrientation(LinearLayout.HORIZONTAL); return l; }
    private LinearLayout rowWrap(){ LinearLayout l=new LinearLayout(this); l.setOrientation(LinearLayout.HORIZONTAL); l.setGravity(Gravity.LEFT); return l; }
    private LinearLayout col(){ LinearLayout l=new LinearLayout(this); l.setOrientation(LinearLayout.VERTICAL); return l; }
    private TextView label(String s,int sp,int color,int style){ return AeDesign.text(this,s,sp,color,style); }
    private void saveProject(boolean visible){ if(store!=null&&project!=null){ if(visible && saveStatus!=null) saveStatus.setText("Saving..."); store.save(project); if(visible && saveStatus!=null) handler.postDelayed(()->saveStatus.setText("Saved"),350); } }
    private String fmt(float sec){ int s=Math.round(sec); return String.format(Locale.US,"%02d:%02d",s/60,s%60); }
    private int dp(int v){ return AeDesign.dp(this,v); }
    private void toast(String s){ Toast.makeText(this,s,Toast.LENGTH_SHORT).show(); }
}
